/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista; 

import javax.swing.JButton;

public class Panel extends javax.swing.JFrame {
  

    public Panel() {
        initComponents();
       
    }
    public JButton getjbtnClientes() {
        return jbtnClientes;
    }

    public JButton getjbtnEmpleados() {
        return jbtnEmpleados;
    }

    public JButton getjbtnProductos() {
        return jbtnProductos;
    }

    public JButton getjbtnNuevaVenta() {
        return jbtnNuevaVenta;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnEmpleados = new javax.swing.JButton();
        jbtnClientes = new javax.swing.JButton();
        jbtnProductos = new javax.swing.JButton();
        jbtnNuevaVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PANEL DE LA EMPRESA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, -1));

        jbtnEmpleados.setBackground(new java.awt.Color(102, 102, 102));
        jbtnEmpleados.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jbtnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado2.png"))); // NOI18N
        jbtnEmpleados.setText("Empleados");
        jbtnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 280, 60));

        jbtnClientes.setBackground(new java.awt.Color(102, 102, 102));
        jbtnClientes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        jbtnClientes.setText("Clientes");
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 280, 60));

        jbtnProductos.setBackground(new java.awt.Color(102, 102, 102));
        jbtnProductos.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtnProductos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        jbtnProductos.setText("Productos");
        jbtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 280, 60));

        jbtnNuevaVenta.setBackground(new java.awt.Color(102, 102, 102));
        jbtnNuevaVenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbtnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nventa.png"))); // NOI18N
        jbtnNuevaVenta.setText("Nueva Venta");
        jbtnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevaVentaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmpleadosActionPerformed
        
    }//GEN-LAST:event_jbtnEmpleadosActionPerformed

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
       
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductosActionPerformed
       
    }//GEN-LAST:event_jbtnProductosActionPerformed

    private void jbtnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevaVentaActionPerformed
      
    }//GEN-LAST:event_jbtnNuevaVentaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnClientes;
    public javax.swing.JButton jbtnEmpleados;
    public javax.swing.JButton jbtnNuevaVenta;
    public javax.swing.JButton jbtnProductos;
    // End of variables declaration//GEN-END:variables
}
